### ISSUE TITLE
ElasticSearch cluster autodiscovery on EC2

### ISSUE THREAD

**Issue by pmoust** [cgswong/docker-elasticsearch#1]
I am running a cluster of CoreOS machines and use an elasticsearch container to run Elasticsearch.

I 've only been able to have EC2 autodiscovery work by adding `--net=host` during runtime so that the 9200/9300 is bound to host networking. Otherwise, ElasticSearch gets a 503 status I think because containers and internally have a different IP/networking so they try to add themselves in the cluster on two interfaces (the host public/private and the container IF IP).

Have you managed to resolve this?

**Comment by pmoust** [comment]
I would be fine with keeping `--net=host` but the problem is you cannot properly link (in a Docker sense) a container like this.

**Comment by cgswong** [comment]
There's a couple ways you can get clustering without the `--net=host` flag.
1. The recommended method (due to security concerns with multicast) is unicast which is what we use with Service Discovery so IPs/hostnames can be easily retrieved. There's an example unit file, [elasticsearch@service](https://raw.githubusercontent.com/cgswong/docker-elasticsearch/master/services/elasticsearch%40.service) which shows how to do this manually though we are actually using [Registrator](https://github.com/gliderlabs/registrator). Essentially, before/after each ES instance starts the IP of its Docker host is stored in a central repository such as [etcd](http://www.etcd.io) or [consul](http://www.consul.io) to name just two of the more popular options. Just prior to the each ES container starting it reviews this central repository for all IPs and uses them as input to `discovery.zen.ping.unicast.hosts`. Since you are in AWS, you can also use the included [AWS Cloud Plugin for Elasticsearch](https://github.com/elastic/elasticsearch-cloud-aws) which uses the AWS API for the same unicast discovery mechanism. You can of course provide the IP addresses manually but Service Discovery makes things much easier and is what you'd use in production.
2. Another option is using an SDN solution such as [weave](http://weave.works) or [consul DNS](http://consul.io) so each container has it's own IP/hostname and is known. I believe consul DNS is still only unicast since it's just giving you DNS but [Weave Net](http://weave.works/net/index.html) would enable multicast.

**Comment by pmoust** [comment]
@cgswong I could not expect a better sum-up/answer. Thanks a lot!
